$ErrorActionPreference = "Stop"

$Repo = Split-Path -Parent $MyInvocation.MyCommand.Path
$ApiProject = Join-Path $Repo "L1\api\L1Api.csproj"
$Ui = Join-Path $Repo "l1-ui"

Write-Host "== Chitragupta Helpdesk local apply ==" -ForegroundColor Cyan
Set-Location $Repo

# next-env.d.ts is regenerated by Next and must not block a fast-forward update.
git restore -- l1-ui/next-env.d.ts 2>$null
$dirty = git status --porcelain
if ($dirty) {
    Write-Host $dirty
    throw "Working tree has local changes. Refusing to overwrite them."
}

Write-Host "Updating main..." -ForegroundColor Cyan
git pull --ff-only origin main

Write-Host "Validating UI..." -ForegroundColor Cyan
Set-Location $Ui
npm run check
npm run build
Set-Location $Repo
git restore -- l1-ui/next-env.d.ts 2>$null

Write-Host "Restarting L1 API..." -ForegroundColor Cyan
Get-Process L1Api -ErrorAction SilentlyContinue | Stop-Process -Force
dotnet build $ApiProject

Start-Process powershell.exe -ArgumentList @(
    "-NoExit",
    "-Command",
    "Set-Location '$Repo'; dotnet run --project '$ApiProject' --no-build --launch-profile http"
)

$ready = $false
for ($i = 0; $i -lt 15; $i++) {
    Start-Sleep -Seconds 1
    try {
        $null = Invoke-RestMethod "http://127.0.0.1:5116/api/config"
        $ready = $true
        break
    } catch {}
}
if (-not $ready) { throw "L1 API did not become ready on port 5116." }

Write-Host "Checking Helpdesk UI..." -ForegroundColor Cyan
$uiReady = $false
try {
    $response = Invoke-WebRequest "http://127.0.0.1:3417/admin" -UseBasicParsing -TimeoutSec 2
    $uiReady = $response.StatusCode -ge 200 -and $response.StatusCode -lt 500
} catch {}

if (-not $uiReady) {
    Start-Process powershell.exe -ArgumentList @(
        "-NoExit",
        "-Command",
        "Set-Location '$Ui'; npm run dev -- -p 3417"
    )

    for ($i = 0; $i -lt 25; $i++) {
        Start-Sleep -Seconds 1
        try {
            $response = Invoke-WebRequest "http://127.0.0.1:3417/admin" -UseBasicParsing -TimeoutSec 2
            if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500) {
                $uiReady = $true
                break
            }
        } catch {}
    }
}
if (-not $uiReady) { throw "Helpdesk UI did not become ready on port 3417." }

$dirtyAfter = git status --porcelain
if ($dirtyAfter) {
    Write-Host $dirtyAfter
    throw "Apply completed but the repository is not clean."
}

Write-Host ""
Write-Host "Ready. API :5116 and Helpdesk UI :3417 are running." -ForegroundColor Green
Write-Host "Refresh http://localhost:3417/admin" -ForegroundColor Green
