#!/usr/bin/env python3
"""Bridge from Chitragupta's Python/MCP runtime to XS Builder's live-schema
read-query compiler.

Chitragupta owns ticket reasoning, ticket/run audit state, and execution.
XS Builder owns the deterministic XStudio/SQL contract for the common
single-table read path: live table discovery, column validation, structured
filters/order, identifier quoting, and final SELECT compilation.

There is deliberately NO local Python fallback. If XS Builder is unavailable,
the tool fails explicitly rather than silently reviving a second query compiler
with different semantics.

Required runtime configuration:
  XSBUILDER_CONNECTION   Saved XS Builder connection profile name or ID.

Optional:
  XSBUILDER_CLI          Executable/path for the xsb CLI. Defaults to "xsb".
                         On Windows this may be a full path to xsb.exe.

Hard support boundary for Chitragupta investigation reads:
  XStudio_Helpdesk
  XStudio_Xbatch
No other database is accepted by this bridge even though XS Builder itself is
generic and can inspect other XStudio databases for its own purposes.
"""
from __future__ import annotations

import json
import os
import subprocess
from typing import Any, Optional

ALLOWED_DATABASES = frozenset({"XStudio_Helpdesk", "XStudio_Xbatch"})


def _require_database(database: str) -> str:
    for allowed in ALLOWED_DATABASES:
        if database.lower() == allowed.lower():
            return allowed
    raise ValueError(
        f"Database '{database}' is outside Chitragupta's investigation boundary. "
        f"Allowed databases: {', '.join(sorted(ALLOWED_DATABASES))}."
    )


def compile_read_query(
    *,
    database: str,
    table: str,
    columns: list[str],
    filters: Optional[list[dict[str, Any]]] = None,
    order_by: Optional[list[dict[str, Any]]] = None,
    top: int = 100,
    schema: str = "dbo",
) -> dict[str, Any]:
    """Ask XS Builder to live-discover + compile one structured SELECT.

    The returned SQL is generated by XS Builder after validating every
    referenced column against the live table. Chitragupta executes it through
    its own run-bound audited read path; XS Builder does not execute the final
    SELECT.
    """
    canonical_database = _require_database(database)
    if not table or not columns:
        raise ValueError("table and at least one explicit output column are required")
    if top < 1 or top > 1000:
        raise ValueError("top must be between 1 and 1000")

    connection = os.environ.get("XSBUILDER_CONNECTION")
    if not connection:
        raise RuntimeError(
            "XSBUILDER_CONNECTION is not configured. Set it to the saved XS Builder "
            "SQL connection profile name or ID used for this server."
        )

    request = {
        "database": canonical_database,
        "schema": schema,
        "table": table,
        "columns": columns,
        "filters": filters or [],
        "orderBy": order_by or [],
        "top": top,
    }

    cli = os.environ.get("XSBUILDER_CLI", "xsb")
    result = subprocess.run(
        [
            cli,
            "compile-read-query",
            "--connection",
            connection,
            "--request-json",
            json.dumps(request, separators=(",", ":")),
        ],
        capture_output=True,
        text=True,
        encoding="utf-8",
        timeout=45,
        check=False,
    )
    if result.returncode != 0:
        message = (result.stderr or result.stdout or "XS Builder query compilation failed").strip()
        raise RuntimeError(f"XS Builder compile-read-query failed ({result.returncode}): {message}")

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            "XS Builder returned non-JSON output from compile-read-query: "
            + result.stdout[:1000]
        ) from exc

    if not payload.get("ok") or not payload.get("sql"):
        raise RuntimeError(f"XS Builder did not return a compiled query: {payload}")
    if _require_database(str(payload.get("database"))) != canonical_database:
        raise RuntimeError("XS Builder returned a database different from the requested allowed database")
    return payload


if __name__ == "__main__":
    # Intentional smoke-test shape only; requires the same env configuration as
    # production and still performs no final SELECT execution.
    print(json.dumps(compile_read_query(
        database="XStudio_Helpdesk",
        table="Hermes_L2_Response_Trn_Tbl",
        columns=["ID", "TicketID", "ProcessStatus"],
        top=3,
    ), indent=2))
